import { defineConfig } from 'vite';
import react from '@vitejs/plugin-react';
import wasm from 'vite-plugin-wasm';
import { fileURLToPath } from 'node:url';

// The compiled counter contract lives in the repo-root `managed/` directory
// (generated by `npm run compile`). Alias it so the UI can import the
// contract bindings without leaving the frontend workspace.
// Falls back to public/contract if managed/ is not available (e.g., Vercel build).
const contractEntry = fileURLToPath(
  new URL('../public/contract/index.js', import.meta.url),
);

export default defineConfig({
  cacheDir: './.vite',
  build: {
    target: 'esnext',
    minify: false,
    rollupOptions: {
      output: {
        manualChunks: {
          wasm: ['@midnight-ntwrk/onchain-runtime-v3'],
        },
      },
    },
    commonjsOptions: {
      transformMixedEsModules: true,
      extensions: ['.js', '.cjs'],
      ignoreDynamicRequires: true,
    },
  },
  plugins: [
    react(),
    wasm(),
    {
      name: 'wasm-module-resolver',
      resolveId(source, importer) {
        if (
          source === '@midnight-ntwrk/onchain-runtime-v3' &&
          importer &&
          importer.includes('@midnight-ntwrk/compact-runtime')
        ) {
          return { id: source, external: false, moduleSideEffects: true };
        }
        return null;
      },
    },
  ],
  optimizeDeps: {
    esbuildOptions: {
      target: 'esnext',
      supported: { 'top-level-await': true },
      platform: 'browser',
      format: 'esm',
      loader: { '.wasm': 'binary' },
    },
    include: ['@midnight-ntwrk/compact-runtime'],
    exclude: [
      '@midnight-ntwrk/onchain-runtime-v3',
      '@midnight-ntwrk/onchain-runtime-v3/midnight_onchain_runtime_wasm_bg.wasm',
      '@midnight-ntwrk/onchain-runtime-v3/midnight_onchain_runtime_wasm.js',
    ],
  },
  resolve: {
    alias: [
      { find: '@contract', replacement: contractEntry },
      // The compiled contract (in repo-root `managed/`, outside this frontend
      // workspace) imports `@midnight-ntwrk/compact-runtime`. Because that
      // file lives outside `frontend/`, Vite won't find `frontend/node_modules`
      // when resolving from it — alias the bare specifier to the local copy.
      {
        find: '@midnight-ntwrk/compact-runtime',
        replacement: fileURLToPath(
          new URL('./node_modules/@midnight-ntwrk/compact-runtime/dist/index.js', import.meta.url),
        ),
      },
      // The SDK imports a *named* `WebSocket` from isomorphic-ws, but its
      // browser build only exposes a default export — re-export it here.
      // RegExp ensures only the bare `isomorphic-ws` specifier is rewritten
      // (so the shim's own `isomorphic-ws/browser.js` import still resolves).
      {
        find: /^isomorphic-ws$/,
        replacement: fileURLToPath(new URL('./src/shims/isomorphic-ws.js', import.meta.url)),
      },
    ],
    extensions: ['.mjs', '.js', '.ts', '.jsx', '.tsx', '.json', '.wasm'],
    mainFields: ['browser', 'module', 'main'],
  },
  server: {
    port: 3000,
    open: true,
    fs: {
      // Allow Vite to read the contract bindings + keys in the repo-root
      // `managed/` directory (outside this frontend folder).
      allow: ['..'],
    },
  },
});
