/// <reference types="vite/client" />

interface ImportMetaEnv {
  readonly VITE_NETWORK_ID?: string;
  readonly VITE_INDEXER_URL?: string;
  readonly VITE_INDEXER_WS_URL?: string;
  readonly VITE_DEFAULT_CONTRACT?: string;
}

interface ImportMeta {
  readonly env: ImportMetaEnv;
}

// Ambient types for the compiled counter contract bindings (generated by
// `npm run compile` into ../../managed/counter/contract/index.js). We only
// declare what the frontend uses; the real types live in the generated
// index.d.ts which is unavailable until the contract is compiled.
declare module '@contract' {
  export const Contract: unknown;
  export function ledger(data: Uint8Array): {
    count: bigint;
    owner: Uint8Array;
    round: unknown;
  };
  export type CircuitKeys = unknown;
  export type Witnesses<T = unknown> = unknown;
  export type Ledger = unknown;
}
